main: net.ddns.lukashuth.main.Main
name: plugin
version: 1
author: me
description: plugin

commands:
   bp:
      description: Backpack
   tpa:
      description: TPA Command
   atp:
      description: ATP Command
      